spring.application.name=token-bucket-rate-limiter

rate-limiter.capacity=20
rate-limiter.refill-rate=5

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.profiles.active=redis
#spring.profiles.active=memory

# =========================
# Actuator Configuration
# =========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Optional: Change the base path if needed
# management.endpoints.web.base-path=/actuator