spring.application.name=token-bucket-rate-limiter

# =========================
# Server Configuration
# =========================
server.port=${PORT:8080}

# =========================
# Rate Limiter Configuration
# =========================
rate-limiter.capacity=${RATE_LIMITER_CAPACITY:20}
rate-limiter.refill-rate=${RATE_LIMITER_REFILL_RATE:5}

# =========================
# Redis Configuration
# =========================
spring.data.redis.url=${REDIS_URL}

# =========================
# Spring Profile
# =========================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:redis}

# =========================
# Actuator Configuration
# =========================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always